package com.ncepu.cloudyi.thrift;

import java.io.IOException;
import java.net.ServerSocket;

import org.apache.thrift.server.TNonblockingServer;
import org.apache.thrift.server.TServer;
import org.apache.thrift.server.TSimpleServer;
import org.apache.thrift.server.TThreadPoolServer;
import org.apache.thrift.server.TThreadedSelectorServer;
import org.apache.thrift.transport.TNonblockingServerSocket;
import org.apache.thrift.transport.TServerSocket;
import org.apache.thrift.transport.TTransportException;

import com.ncepu.cloudyi.thrift.autogenerated.HelloWordService.Processor;
import com.ncepu.cloudyi.thrift.impl.HelloWordServiceImpl;

public class HelloWorldServer {
    public static void main(String[] args) throws IOException, TTransportException {
//        ServerSocket socket = new ServerSocket(7912);
        TNonblockingServerSocket socket = new TNonblockingServerSocket(7912);
        // 传输层使用socket
//        TServerSocket serverTransport = new TServerSocket(socket);
        // processor将线上数据的输入交给HelloWordServiceImpl处理并且将结果返回到线上
        Processor processor = new Processor(new HelloWordServiceImpl());

        // server将这些参数组合起来
//        TServer server = new TSimpleServer(new TSimpleServer.Args(serverTransport).processor(processor));
//        TServer server = new TNonblockingServer(new TNonblockingServer.Args(socket).processor(processor));
        TThreadedSelectorServer server = new TThreadedSelectorServer(new TThreadedSelectorServer.Args(socket)
                .processor(processor));
        System.out.println("Running server...");
        // 调用serve()方法开启监听接收客户端连接
        server.serve();
    }
}
