package com.ncepu.cloudyi.thrift;

import org.apache.thrift.protocol.TBinaryProtocol;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.transport.TNonblockingServerSocket;
import org.apache.thrift.transport.TNonblockingSocket;
import org.apache.thrift.transport.TSocket;
import org.apache.thrift.transport.TTransport;
import org.apache.thrift.transport.layered.TFramedTransport;

import com.ncepu.cloudyi.thrift.autogenerated.HelloWordService;
import com.ncepu.cloudyi.thrift.autogenerated.Request;
import com.ncepu.cloudyi.thrift.autogenerated.RequestType;

public class HelloWordClient {
    public static void main(String[] args) throws Exception {
//        TTransport transport = new TSocket("localhost", 7912);
        TTransport transport = new TFramedTransport(new TSocket("localhost", 7912));
        // 使用二进制协议层
        TProtocol protocol = new TBinaryProtocol(transport);

        // 创建client
        HelloWordService.Client client = new HelloWordService.Client(protocol);
        transport.open();  // 建立连接

        // 第一种请求类型
        Request request = new Request()
                .setType(RequestType.SAY_HELLO).setName("winwill2012").setAge(24);
        System.out.println(client.doAction(request));

        // 第二种请求类型
        request.setType(RequestType.QUERY_TIME).setName("winwill2012");
        System.out.println(client.doAction(request));

        transport.close();  // 请求结束，断开连接
    }
}
