package com.ncepu.cloudyi.thrift.impl;

import org.apache.commons.lang3.StringUtils;
import org.apache.thrift.TException;

import java.util.Date;


import com.ncepu.cloudyi.thrift.autogenerated.HelloWordService;
import com.ncepu.cloudyi.thrift.autogenerated.Request;
import com.ncepu.cloudyi.thrift.autogenerated.RequestException;
import com.ncepu.cloudyi.thrift.autogenerated.RequestType;

public class HelloWordServiceImpl implements HelloWordService.Iface {
    @Override
    public String doAction(Request request) throws RequestException, TException {
        System.out.println("Get request: " + request);
        if (StringUtils.isBlank(request.getName()) || request.getType() == null) {
            throw new RequestException();
        }
        String result = "Hello, " + request.getName();
        if (request.getType() == RequestType.SAY_HELLO) {
            result += ", Welcome!";
        } else {
            result += ", Now is " + new Date().toLocaleString();
        }
        return result;
    }
}
